<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bulk Invoice</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #4a4a4a;
        }
        h2 {
            color: #6b7280;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <h1>Bulk Invoice</h1>
    <h2>Project: {{ $project_name }}</h2>
    <p><strong>Invoice Date:</strong> {{ $invoice_date }}</p>

    <table>
        <thead>
            <tr>
                <th>Donor</th>
                <th>Participant</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($donations as $donation)
                <tr>
                    <td>{{ $donation['donor'] }}</td>
                    <td>{{ $donation['participant'] }}</td>
                    <td>{{ $donation['amount'] }}</td>
                    <td>{{ $donation['currency'] }}</td>
                    <td>{{ $donation['date'] }}</td>
                    <td>{{ $donation['status'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Sponsoring24 Platform</p>
        <p>&copy; {{ now()->year }} Sponsoring24. All rights reserved.</p>
    </div>
</body>
</html>