version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sponsoring24-app
    restart: unless-stopped
    working_dir: /var/www/html
    user: root
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - APP_ENV=local
      - APP_URL=${APP_URL:-http://localhost}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=sponsoring24
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_POST_MAX_SIZE=64M
      - PHP_UPLOAD_MAX_FILESIZE=64M
    command: >
      bash -c "
        mkdir -p /var/www/html/storage/framework/{sessions,views,cache} &&
        mkdir -p /var/www/html/storage/logs &&
        mkdir -p /var/www/html/bootstrap/cache &&
        chown -R www-data:www-data /var/www/html/storage &&
        chown -R www-data:www-data /var/www/html/bootstrap/cache &&
        chmod -R 775 /var/www/html/storage &&
        chmod -R 775 /var/www/html/bootstrap/cache &&
        php-fpm"
    depends_on:
      - db
      - redis
    networks:
      - sponsoring24-network

  nginx:
    image: nginx:alpine
    container_name: sponsoring24-nginx
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - sponsoring24-network

  db:
    image: postgres:15-alpine
    container_name: sponsoring24-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sponsoring24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sponsoring24-network

  redis:
    image: redis:alpine
    container_name: sponsoring24-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sponsoring24-network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sponsoring24-node
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_APP_URL=${APP_URL:-http://localhost}
    command: >
      bash -c "
        npm install &&
        npm run dev"
    ports:
      - "5173:5173"
    networks:
      - sponsoring24-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  sponsoring24-network:
    driver: bridge

volumes:
  db-data:
  redis-data: