const Ziggy = {
    url: 'http://localhost',
    port: null,
    defaults: {},
    routes: {
        'language.switch': { uri: 'language/{locale}', methods: ['GET', 'HEAD'], parameters: ['locale'] },
        'dashboard': { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        // memebers
        'dashboard.members.index': { uri: 'members', methods: ['GET', 'HEAD'] },
        'dashboard.members.create': { uri: 'members/create', methods: ['GET', 'HEAD'] },
        'dashboard.members.show': { uri: 'members/{participant}', methods: ['GET', 'HEAD'], parameters: ['participant'] },
        'dashboard.members.edit': { uri: 'members/{participant}/edit', methods: ['GET', 'HEAD'], parameters: ['participant'] },
        'dashboard.members.store': { uri: 'members', methods: ['POST'] },
        'dashboard.members.update': { uri: 'members/{participant}', methods: ['PUT', 'PATCH'], parameters: ['participant'] },
        'dashboard.members.destroy': { uri: 'members/{participant}', methods: ['DELETE'], parameters: ['participant'] },
        'dashboard.members.import': { uri: 'members/import', methods: ['POST'] },
        'dashboard.members.export': { uri: 'members/export', methods: ['GET', 'HEAD'] },
        // projects
        'dashboard.projects.index': { uri: 'projects', methods: ['GET', 'HEAD'] },
        'dashboard.projects.create': { uri: 'projects/create', methods: ['GET', 'HEAD'] },
        'dashboard.projects.edit': { uri: 'projects/{project}/edit', methods: ['GET', 'HEAD'], parameters: ['project'] },
        'dashboard.projects.uploadImage': { uri: 'projects/{project}/upload-image', methods: ['POST'], parameters: ['project'] },
        'dashboard.projects.duplicate': { uri: 'projects/{project}/duplicate', methods: ['POST'], parameters: ['project'] },
        'dashboard.projects.store': { uri: 'projects', methods: ['POST'] },
        'dashboard.projects.update': { uri: 'projects/{project}', methods: ['PUT', 'PATCH'], parameters: ['project'] },
        'dashboard.projects.destroy': { uri: 'projects/{project}', methods: ['DELETE'], parameters: ['project'] },
        'logout': { uri: 'logout', methods: ['POST'] },
        // Add other routes as generated by ziggy:generate
    }
};

export { Ziggy };
export function route(name, params, absolute) {
    let url = Ziggy.routes[name]?.uri || name;
    if (params) {
        Object.keys(params).forEach(key => {
            url = url.replace(`{${key}}`, encodeURIComponent(params[key]));
        });
    }
    return absolute ? `${Ziggy.url}${url}` : url;
}