name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
        coverage: none

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm ci

    - name: Build Assets
      run: npm run build

    - name: Configure Environment
      run: |
        cp .env.example .env
        sed -i 's/APP_ENV=local/APP_ENV=production/' .env
        sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
        sed -i "s|APP_URL=http://localhost|APP_URL=https://your-production-url.com|" .env
        php artisan key:generate

    - name: Build Production Assets
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    # Removed GitHub Pages deployment step 