name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: fundoo_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: fundoo_test
      DB_USERNAME: postgres
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Copy .env.example
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run PHP lint
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff || true
      - name: Run PHPUnit tests
        run: php artisan test --parallel

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint resources/js
      - name: Run Stylelint
        run: npx stylelint "resources/css/**/*.css"
      - name: Run frontend tests
        run: npm run test || true
      - name: Build frontend
        run: npm run build

  deploy:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy (placeholder)
        run: echo "Deploy step here (e.g., rsync, SSH, or GitHub Pages)" 