name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
    - uses: actions/checkout@v4

    - name: Debug Workflow Run
      run: |
        echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
        echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Workflow Run Head Branch: ${{ github.event.workflow_run.head_branch }}"
        echo "Repository: ${{ github.repository }}"
        echo "Artifacts URL: https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts"

    - name: Wait for Artifacts
      run: |
        max_attempts=30
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts to check for artifacts..."
          artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts")
          
          if echo "$artifacts" | jq -e '.artifacts | length > 0' > /dev/null; then
            echo "Artifacts found!"
            echo "$artifacts" | jq '.artifacts[] | {name: .name, expired: .expired}'
            exit 0
          fi
          
          echo "No artifacts found yet, waiting..."
          sleep 10
          attempt=$((attempt + 1))
        done
        
        echo "Failed to find artifacts after $max_attempts attempts"
        exit 1

    - name: Download Build Artifacts
      id: download-artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build-artifacts
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Artifact Download
      if: steps.download-artifacts.outcome == 'success'
      run: |
        echo "Artifact download status: ${{ steps.download-artifacts.outcome }}"
        echo "Current directory: $(pwd)"
        echo "Listing build-artifacts directory:"
        ls -la build-artifacts || echo "build-artifacts directory not found"
        echo "Listing build-artifacts/build directory:"
        ls -la build-artifacts/build || echo "build directory not found"
        echo "Listing build-artifacts/vendor directory:"
        ls -la build-artifacts/vendor || echo "vendor directory not found"

    - name: Verify Artifact Contents
      if: steps.download-artifacts.outcome == 'success'
      run: |
        if [ ! -d "build-artifacts" ]; then
          echo "Error: build-artifacts directory not found"
          exit 1
        fi
        if [ ! -d "build-artifacts/build" ]; then
          echo "Error: build directory not found in artifacts"
          exit 1
        fi
        if [ ! -d "build-artifacts/vendor" ]; then
          echo "Error: vendor directory not found in artifacts"
          exit 1
        fi
        echo "Artifact contents verified successfully"

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd /var/www/fundoo
          git pull origin main
          mkdir -p public/build
          cp -r build-artifacts/build/* public/build/
          cp -r build-artifacts/vendor vendor/
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.3-fpm
          sudo systemctl restart nginx