name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: .
        run_id: ${{ github.event.workflow_run.id }}

    - name: Verify Artifacts
      run: |
        if [ ! -d "public/build" ]; then
          echo "Error: public/build directory not found"
          exit 1
        fi
        if [ ! -d "vendor" ]; then
          echo "Error: vendor directory not found"
          exit 1
        fi
        echo "Artifacts verified successfully"

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd /var/www/fundoo
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.3-fpm
          sudo systemctl restart nginx

    - name: Notify on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: good
        SLACK_TITLE: Deployment Successful
        SLACK_MESSAGE: 'Deployment to production completed successfully!'
        SLACK_FOOTER: 'Fundoo Platform'

    - name: Notify on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: danger
        SLACK_TITLE: Deployment Failed
        SLACK_MESSAGE: 'Deployment to production failed!'
        SLACK_FOOTER: 'Fundoo Platform' 