name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
    - name: Download Artifacts from CI
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: CI
        name: build-artifacts
        path: build-artifacts
        branch: main
        workflow_conclusion: success

    - name: Check Downloaded Artifacts
      run: |
        ls -la build-artifacts
        ls -la build-artifacts/build || echo "No build dir"
        ls -la build-artifacts/vendor || echo "No vendor dir"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/fundoo
          git pull origin main
          mkdir -p public/build
          cp -r build-artifacts/build/* public/build/ || echo "No build to copy"
          cp -r build-artifacts/vendor vendor/ || echo "No vendor to copy"
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.3-fpm
          sudo systemctl restart nginx
